version: 2.1

orbs:
  go: circleci/go@1

jobs:
  gen-apidocs:
    executor:
      name: go/default
      tag: '1.19.1'
    parameters:
      committer_name:
        type: string
        default: TriggerMesh Bot
      committer_email:
        type: string
        default: bot@triggermesh.com
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "aa:03:46:c4:da:eb:da:02:ad:c0:3a:bc:5f:62:02:9c"
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Configuring git
          command: |
            git config --global user.name '<< parameters.committer_name >>'
            git config --global user.email '<< parameters.committer_email >>'
      - run:
          name: Cloning docs repository
          command: git clone --single-branch git@github.com:triggermesh/docs.git tm-docs
      - run:
          name: Run gen-apidocs
          command:  TRIGGERMESH_COMMIT=${CIRCLE_TAG:-$CIRCLE_SHA1} make gen-apidocs
          environment:
            DOCS_OUTPUT_DIR: ~/project/tm-docs/docs/reference/
      - run:
          name: Committing updates to triggermesh/docs
          working_directory: tm-docs/
          command: |
            if ! git diff --exit-code --quiet; then
              git --no-pager diff
              git add docs/reference/
              git commit -m "Generated with gen-crd-api-reference-docs on git commit triggermesh-core:${CIRCLE_TAG:-${CIRCLE_SHA1}}"
              git push origin main
            fi

workflows:
  test-and-publish:
    jobs:
      - gen-apidocs:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              only: main
