# This role provides readonly access to "Addressable" duck types.
# All the rules it contains get aggregated into the "addressable-resolver" ClusterRole.
# https://github.com/knative/eventing/blob/release-0.26/config/core/roles/addressable-resolvers-clusterrole.yaml#L15-L28
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggermesh-core-addressable-resolver
  labels:
    app.kubernetes.io/part-of: triggermesh
    duck.knative.dev/addressable: 'true'
rules:
# +rbac-check
- apiGroups:
  - eventing.triggermesh.io
  resources:
  - redisbrokers
  verbs:
  - get
  - list
  - watch
