name: Container images

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  container_image:
    name: Build container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_SERVICEACCOUNT_KEY }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gcr.io/triggermesh/triggermesh-core
          tags: |
            type=semver,pattern={{raw}}
            latest

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: cmd/core-controller/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
